name: CI

on:
  push:
    branches:
      - Asim-work

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2.5.1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: |
        npm install
        npm install -g certsync

    - name: Build
      run: npm run build

    - name: Test
      run: npm run test
