name: CI

on:
  push:
    branches:
      - Asim-work

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install certsync

    - name: Lint
      run: |
        pip install pylint
        pylint --fail-under=9 my_module.py

    - name: Test
      run: pytest

    - name: Build
      run: python setup.py sdist bdist_wheel
