name: CI

on:
  push:
    branches:
      - Asim-work

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint
      run: |
        pip install pylint
        pylint --fail-under=9 feature_1.py

    - name: Test
      run: pytest

    - name: Build
      run: python setup.py sdist bdist_wheel
